pokemonweb/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views as accounts_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/signup/", accounts_views.signup, name="signup"),
    path("accounts/login/",  auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("", include("trainers.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trainers/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path("", views.home, name="home"),
	path("your_trainers/", views.your_trainers, name="your_trainers"),
	path("pokemon_list/", views.pokemon_list, name="pokemon_list"),
	path("search/<str:search>/<int:pk>/", views.search, name="search"),
	path("pokemon_list/add_pokemon/", views.add_pokemon, name="add_pokemon"),
	path("pokemon_list/edit_pokemon/<int:pk>/", views.edit_pokemon, name="edit_pokemon"),
	path("pokemon_list/remove_poken/<int:pk>/", views.remove_pokemon, name="remove_pokemon"),
	path("pokemon_list/verify_pokemon/<int:pk>/", views.verify_pokemon, name="verify_pokemon"),
	path("your_trainers/create_trainer/", views.create_trainer, name="create_trainer"),
	path("your_trainers/edit_trainer/<int:pk>/", views.edit_trainer, name="edit_trainer"),
	path("your_trainers/remove_trainer/<int:pk>/", views.remove_trainer, name="remove_trainer"),
	path("trainer_pokemon_list/<int:pk>/", views.trainer_pokemon_list, name="trainer_pokemon_list"),
	path("trainer_pokemon_list/trainer_add_pokemon/<int:pk>", views.trainer_add_pokemon, name="trainer_add_pokemon"),
	path("trainer_pokemon_list/release_owned_pokemon/<int:pk>/", views.release_trainer_pokemon, name="release_trainer_pokemon"),
	path("your_pokemons/<int:pk>", views.your_pokemons, name="your_pokemons"),
]

trainers/models.py
from django.db import models
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Pokemon(models.Model):
	#list of pokemon types available
	type_list = [
		('BUG', 'BUG'),
		('DARK', 'DARK'),
		('DRAGON', 'DRAGON'),
		('ELECTRIC', 'ELECTRIC'),
		('FAIRY', 'FAIRY'),
		('FIGHTING', 'FIGHTING'),
		('FIRE', 'FIRE'),
		('FLYING', 'FLYING'),
		('GHOST','GHOST'),
		('GRASS', 'GRASS'),
		('GROUND','GROUND'),
		('ICE','ICE'),
		('NORMAL', 'NORMAL'),
		('POISON', 'POISON'),
		('PSYCHIC', 'PSYCHIC'),
		('ROCK', 'ROCK'),
		('STEEL', 'STEEL'),
		('WATER', 'WATER'),
		('???', '???'),
	]
	name = models.CharField(max_length=32)
	pokedex_no = models.IntegerField(unique=True)
	type1 = models.CharField(max_length=10, choices=type_list)
	type2 = models.CharField(max_length=10, choices=type_list, blank=True)
	photo = models.ImageField(upload_to="pokemon_photos", null=True)
	description = models.TextField(null=True)
	is_verified = models.BooleanField(default=False)

	def verify(self):
		self.is_verified = True


	def __str__(self):
		return self.name

class Trainer(models.Model):
	sex_choices = (
		('F', 'FEMALE'),
		('M', 'MALE'),
	)
	user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
	photo = models.ImageField(upload_to="trainer_photos", blank=True)
	name = models.CharField(max_length=32, blank=True)
	sex = models.CharField(max_length=1, choices=sex_choices, blank=True)
	#Many to many relationship with intemnediary PokemonOwnership
	pokemons = models.ManyToManyField(Pokemon, through='PokemonOwnership', blank=True)

	def __str__(self):
		return self.name+" [USER: "+str(self.user)+"]"

#intermediary model for Trainer.pokemon
class PokemonOwnership(models.Model):
	sex_choices = (
		('F', 'FEMALE'),
		('M', 'MALE'),
		('G', 'GENDERLESS'),
	)
	shiny_choices = (
		(True, 'YES'),
		(False, 'NO'),
	)

	trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE)
	pokemon = models.ForeignKey(Pokemon, on_delete=models.CASCADE, limit_choices_to={"is_verified":True})
	nickname =  models.CharField(max_length=32, blank=True)
	level = models.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(100)])
	sex = models.CharField(max_length=1, choices=sex_choices)
	shiny = models.BooleanField(choices=shiny_choices, default=False)

	def __str__(self):
		return str(self.trainer) + "-" + str(self.pokemon)

# @receiver(post_save, sender=User)
# def createUserTrainer(sender, instance, created, **kwargs):
# 	if created:
# 		Trainer.objects.create(user=instance)

# @receiver(post_save, sender=User)
# def saveUserTrainer(sender, instance, **kwargs):
# 	instance.trainer.save()

trainers/forms.py
from django import forms
from .models import Trainer, Pokemon, PokemonOwnership

class TrainerForm(forms.ModelForm):
	class Meta:
		model = Trainer
		fields = ('name', 'sex', 'photo', )

class PokemonForm(forms.ModelForm):
	class Meta:
		model = Pokemon
		fields = ('pokedex_no', 'name', 'type1', 'type2', 'photo', 'description', )

class PokemonOwnershipForm(forms.ModelForm):
	class Meta:
		model = PokemonOwnership
		fields = ('pokemon', 'nickname', 'level', 'sex', 'shiny',)		

trainers/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Trainer, Pokemon, PokemonOwnership
from .forms import TrainerForm, PokemonForm, PokemonOwnershipForm
from django.contrib.auth.decorators import login_required
from itertools import chain
from django.contrib import messages

# Create your views here.

@login_required
def home(request):
	trainers = Trainer.objects.filter(user=request.user.id)
	return render(request, "trainers/home.html", {"trainers":trainers})

@login_required	
def your_trainers(request):
	trainers = Trainer.objects.filter(user=request.user.id)
	return render(request, "trainers/your_trainers.html", {"trainers":trainers})

@login_required	
def create_trainer(request):
	if request.method == "POST":
		form = TrainerForm(request.POST, request.FILES)
		if form.is_valid():
			post = form.save(commit=False)
			post.user = request.user
			post.save()
			messages.success(request, "Trainer added!")
			return redirect("home")
	else:
		form = TrainerForm()
	return render(request, "trainers/create_trainer.html", {"form":form})

@login_required	
def edit_trainer(request, pk):
	trainer =  get_object_or_404(Trainer, pk=pk)
	if request.method == "POST":
		form = TrainerForm(request.POST, request.FILES, instance=trainer)
		if form.is_valid():
			form.save()
			messages.success(request, "Trainer saved!")
			return redirect("/#" + str(trainer.pk))
	else:
		form = TrainerForm(instance=trainer)
	return render(request, "trainers/create_trainer.html", {"form":form})

@login_required	
def remove_trainer(request, pk):
	trainer = get_object_or_404(Trainer, pk=pk)
	trainer.delete()
	messages.success(request, "Trainer deleted!")
	return redirect("home")

@login_required	
def pokemon_list(request):
	try:
		q = request.GET.get("q")
	except:
		q = None
	if q:
		pokemons = Pokemon.objects.filter(name__unaccent__icontains=q)
		context = {"pokemons": pokemons}
		template = "trainers/pokemon_list.html"
	else:
		pokemons = Pokemon.objects.all().order_by("pokedex_no")
		context = {"pokemons": pokemons}
		template = "trainers/pokemon_list.html" 
	return render(request, template, context)

@login_required	
def add_pokemon(request):
	if request.method == "POST":
		form = PokemonForm(request.POST, request.FILES)
		if form.is_valid():
			pokemon = form.save(commit=False)
			pokemon.name = pokemon.name.capitalize()
			pokemon.save()
			messages.success(request, 'Pokemon added, needs staff verification.')
			return redirect("pokemon_list")
	else:
		form = PokemonForm()
	return render(request, "trainers/add_pokemon.html", {"form":form})

@login_required	
def edit_pokemon(request, pk):
	pokemon = get_object_or_404(Pokemon, pk=pk)
	if request.method == "POST":
		form = PokemonForm(request.POST, request.FILES, instance=pokemon)
		if form.is_valid():
			pokemon = form.save(commit=False)
			pokemon.name = pokemon.name.capitalize()
			pokemon.save()
			messages.success(request, "Pokemon info updated!")
			return redirect("/pokemon_list#"+str(pokemon.pk))
	else:
		form = PokemonForm(instance=pokemon)
	return render(request, "trainers/add_pokemon.html", {"form":form})

@login_required	
def remove_pokemon(request, pk):
	pokemon = get_object_or_404(Pokemon, pk=pk)
	pokemon.delete()
	messages.success(request, "Pokemon removed!")
	return redirect("pokemon_list")

@login_required	
#verify pokemon record validity for admin
def verify_pokemon(request, pk):
	pokemon = get_object_or_404(Pokemon, pk=pk)
	pokemon.verify()
	pokemon.save()
	messages.success(request, "Pokemon Verified")
	return redirect("pokemon_list")

#search bar views
@login_required	
def search(request, search, pk):
	#get search query from link
	try:
		query = request.GET.get("q")
	except:
		query = None

	#checks what page to search and display
	if search == "pokemon_list":	
		if query:
			pokemons = Pokemon.objects.filter(name__icontains=query).order_by("pokedex_no")
		else:
			pokemons = Pokemon.objects.all().order_by("pokedex_no")
		context = {"pokemons": pokemons}
		template = "trainers/pokemon_list.html" 
	elif search == "trainer":
		if query:
			trainers = Trainer.objects.filter(user=request.user.id).filter(name__icontains=query)
		else:
			trainers = Trainer.objects.filter(user=request.user.id)
		context = {"trainers": trainers}
		template = "trainers/your_trainers.html" 
	elif search == "your_pokemons":
		if query:
			pokemons = PokemonOwnership.objects.filter(trainer__user = pk, pokemon__name__icontains=query)
		else:
			pokemons = PokemonOwnership.objects.filter(trainer__user = pk)
		context = {"pokemons": pokemons}
		template = "trainers/your_pokemons.html"  
	elif search == "trainer_pokemon_list":
		trainer = Trainer.objects.get(pk=pk)
		if query:
			pokemons = PokemonOwnership.objects.filter(trainer=pk, pokemon__name__icontains=query)
		else:
			pokemons = PokemonOwnership.objects.filter(trainer=pk)
		context = {"pokemons": pokemons, "trainer":trainer}
		template = "trainers/trainer_pokemon_list.html"
	context.update({"query":query})	  	
	return render(request, template, context)

@login_required	
def trainer_pokemon_list(request, pk):
	trainer = Trainer.objects.get(pk=pk)
	if not trainer.user == request.user:
		return redirect("home")
	pokemons = PokemonOwnership.objects.filter(trainer=pk)
	# pokemons = trainer.pokemons.all()
	return render(request, "trainers/trainer_pokemon_list.html", {"pokemons":pokemons, "trainer":trainer})

@login_required	
def trainer_add_pokemon(request, pk):
	trainer = get_object_or_404(Trainer, pk=pk)
	if request.method == "POST":
		form = PokemonOwnershipForm(request.POST)
		if form.is_valid():
			pokemon = form.save(commit=False)
			pokemon.trainer = trainer
			pokemon.save()
			messages.success(request, "New pokemon added to trainer!")
			return redirect("trainer_pokemon_list", pk=trainer.pk)
	else:
		form = PokemonOwnershipForm	
	return render(request, "trainers/trainer_add_pokemon.html", {"form":form, "trainer":trainer})


@login_required	
def release_trainer_pokemon(request, pk):
	pokemon = get_object_or_404(PokemonOwnership, pk=pk)
	trainer = pokemon.trainer.id
	pokemon.delete()
	messages.success(request, "Pokemon Released!")
	return redirect("trainer_pokemon_list", pk=trainer)

@login_required	
def your_pokemons(request, pk):
	pokemons = PokemonOwnership.objects.filter(trainer__user = pk)
	return render(request, "trainers/your_pokemons.html", {"pokemons":pokemons})

trainers/templates/trainers/add_pokemon.html
{% extends "trainers/pokemon_web_template.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}
	<div class="col-md-8 col-md-offset-2">
		{% if form.errors %}
 			<p>There is something wrong with the form</p>
 		{% endif %}
		<form method="post" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form|crispy }}
			<button class="btn btn-submit pull-right" type="submit">Save Pokemon</button>
		</form>
	</div>
{% endblock %}

trainers/templates/trainers/create_trainer.html
{% extends "trainers/pokemon_web_template.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}
 	<div class="content col-md-8 col-md-offset-2">
 		{% if form.errors %}
 			<p>There is something wrong with the form</p>
 		{% endif %}
 		<form method="post" enctype="multipart/form-data" >
 			{% csrf_token %}
			{{ form|crispy }}
			<button type="submit" class="btn btn-submit pull-right">Done</button>
 		</form>
 	</div>
{% endblock %}

trainers/templates/trainers/home.html
{% extends 'trainers/pokemon_web_template.html' %}
{% load static %}
{% block body %}
	<div class="row">
		<div class="header-section text-center">
			<h1>Welcome, {{ user.username }} </h1>
			<p>Here is the list of trainers you've created.</p>
			<hr class="bottom-line">
		</div>
		{% for trainer in trainers %}
			<div class="col-md-4 col-sm-6">
				<div class="card">
					<img class="card-img-top" src="{{ trainer.photo.url }}" alt="Card image cap">
					<div class="card-body">
						<h5 class="card-title">{{ trainer.name }}</h5>
						<p class="card-text">{{ trainer.get_sex_display }}</p>
						<a href="{% url 'trainer_pokemon_list' pk=trainer.pk %}" class="btn btn-primary btn-sm">View Pokemons</a>
						<div class="fea">
						  	<a href="{% url 'edit_trainer' pk=trainer.pk %}"  class="btn btn-default btn-sm" title="edit trainer"><span class="glyphicon glyphicon-pencil"></span></a> 
						  	<a href="{% url 'remove_trainer' pk=trainer.pk %}" class="btn btn-default btn-sm" title="delete trainer"><span class="glyphicon glyphicon-remove"></span></a>
						</div>
					</div>
				</div>
			</div>
		{% endfor %}
		<div class="col-md-4 col-sm-6">
			<div class="card">
				<a class="btn btn-icon" href="{% url 'create_trainer' %}" title="add trainer"><i class="glyphicon glyphicon-plus"></i></a>
			</div>
		</div>
	</div>
{% endblock %}

trainers/templates/trainers/pokemon_list.html
{% extends 'trainers/pokemon_web_template.html' %}
{% load static %}
{% block body %}
	<div class="header-section">
		{% if user.is_authenticated %}
			<a href="{% url 'add_pokemon' %}" class="btn btn-primary pull-right">Add a Pokemon</a>
		{% endif %}
		<h1>Pokedex</h1>
		<hr>
		<hr class="bottom-line">
	</div>
	
	{% for pokemon in pokemons %}
		{% if pokemon.is_verified or user.is_staff %}
			<div class="col-md-8 col-md-offset-2" id="{{ pokemon.pk }}">
				<div class="card card-short">
				  <img class="card-img-top-short" src="{{ pokemon.photo.url }}" alt="Card image cap">
				  <div class="card-body">
				  	<div class="col-md-6">
					  	<small class="text-muted">Pokedex # {{ pokemon.pokedex_no }}</small>
					    <h3 class="card-title card-title-short">{{ pokemon.name }}</h3>
					    <small class="type-capsul type-{{ pokemon.type1 }}">{{ pokemon.type1 }}</small>
					    {% if pokemon.type2 %}
					    	<small class="type-capsul type-{{ pokemon.type2 }}">{{ pokemon.type2 }}</small>
					    {% endif %}
					</div>
					<div class="col-md-6 pull-right">
						{% if user.is_staff %}
						  	<a href="{% url 'remove_pokemon' pk=pokemon.pk %}" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-remove"></span></a>
						  	{% if not pokemon.is_verified %}
						  		<a href="{% url 'verify_pokemon' pk=pokemon.pk %}" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-ok"></span></a>
						  	{% endif %}
						  	<a href="{% url 'edit_pokemon' pk=pokemon.pk %}" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-pencil"></span></a>
						  {% endif %}
					</div>
					<div class="col-md-12">
				    	<p class="card-text">{{ pokemon.description }}</p>
				    </div>
				  </div>
				</div>
			</div>
		{% endif %}
	{% endfor %}
{% endblock %}

trainers/templates/trainers/pokemon_web_template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Pokemon Web!</title>
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans|Candal|Alegreya+Sans">
	<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css'  %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/imagehover.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
</head>

<body style="background-image:url({% static 'img/bg.jpg' %});">
	<div class="container" style="background-color: #fff">
		<!--Navigation bar-->
		<nav class="navbar navbar-default navbar-fixed-top" style="position: unset;">
			<div class="pull-left nav-icon">
				<img src="{% static 'img/download.png' %}">
			</div>
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>

				<a class="navbar-brand" href="{% url 'your_trainers' %}" style="margin-left: 0;">Pok&eacute;mon<span>WEB</span></a>
			</div>
			<div class="collapse navbar-collapse" id="myNavbar" >
				<ul class="nav navbar-nav navbar-right" style="margin:0px;">
					<li><a href="{% url 'your_trainers' %}">Home</a></li>
					{% if user.is_authenticated %}
						<li><a href="{% url 'your_pokemons' pk=user.pk %}">Pokemons</a></li>
					<li><a href="{% url 'pokemon_list' %}">Pokedex</a></li>
						<li><a href="{% url 'logout' %}">Logout</a></li>
					{% else %}
						<li><a href="{% url 'login' %}">Login</a></li>
					{% endif %}
				</ul>
			</div>
			{% if user.is_authenticated %}
			{% if query %}
				<h4 class="pull-left">Search results for "{{query}}"</h4>
			{% endif %}
			<div class="cta-2-form text-right ">
				{% if "/your_pokemons/" in request.path  %}
					<form action="{% url 'search' search='your_pokemons' pk=user.pk %}" id="" role="search">
				{% elif request.path == "/your_trainers/" or '/trainer/' in request.path %}
					<form action="{% url 'search' search='trainer' pk=user.pk %}" id="" role="search">
				{% elif "/pokemon_list/" in request.path %}
					<form action="{% url 'search' search='pokemon_list' pk=user.pk %}" id="" role="search">
				{% elif "/trainer_pokemon_list/" in request.path %}
					<form action="{% url 'search' search='trainer_pokemon_list' pk=trainer.pk %}" id="" role="search">
				{% endif %}
					<input name="q" placeholder="Search here.." type="text" class="search-text">
					<button class="cta-2-form-submit-btn" type="submit"><span class="glyphicon glyphicon-search"></span></button>
				</form>
			</div>
			{% endif %}
		</nav>
		<div class="container-fluid">
			{% block body %}
            {% endblock %}
		</div>
		<!--Footer-->
		<footer id="footer" class="footer text-center">
			ALl rights reserved 2019
		</footer>
		<!--/ Footer-->
	</div>

	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/jquery.easing.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/custom.js' %}"></script>
	<script src="{% static 'js/contactform.js' %}"></script>
	<script src="{% static 'js/sweetalert.min.js' %}"></script>
	{% if messages %}
		{% for message in messages %}
			<script type="text/javascript">
				swal("{{message.tags}}","{{message}}","{{message.tags}}")
			</script>
		{% endfor %}
	{% endif %}

</body>

</html>

trainers/templates/trainers/results.html
{% extends "trainers/pokemon_web_template.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}
	<h1> search {{query}}</h1>
{% endblock %}

trainers/templates/trainers/trainer_add_pokemon.html
{% extends "trainers/pokemon_web_template.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}
	<div class="col-md-8 col-md-offset-2">
		{% if form.errors %}
 			<p>There is something wrong with the form</p>
 		{% endif %}
		<form method="post">
			{% csrf_token %}
			{{ form|crispy }}
			<button class="btn btn-submit pull-right" type="submit">Save Pokemon</button>
		</form>
	</div>
{% endblock %}

trainers/templates/trainers/trainer_pokemon_list.html
{% extends 'trainers/pokemon_web_template.html' %}
{% load static %}
{% block body %}
	<div class="header-section">
		{% if user.is_authenticated %}
			<a href="{% url 'trainer_add_pokemon' pk=trainer.pk %}" class="btn btn-primary pull-right">Add a Pokemon</a>
		{% endif %}
		<h1>{{trainer.name}}'s Pokemons</h1>
		<hr>
		<hr class="bottom-line">
	</div>
	{% for pokemon in pokemons %}
		{% if pokemon.pokemon.is_verified %}
			<div class="col-md-3">
				<div class="card card-vertical card-short">
					<img class="card-img-top-short" src="{{ pokemon.pokemon.photo.url }}" alt="Card image cap">
					<div class="card-body">
						<div class="col-md-12">
							<small class="text-muted">
								{% if pokemon.nickname %}
							 		{{ pokemon.nickname }}
							 	{% else %}
							 		{{ pokemon.pokemon.name }}
								{% endif %}
							</small>
							<h3 class="card-title card-title-short">
								{{ pokemon.pokemon.name }}
							</h3>
							<small>Lvl {{ pokemon.level }}</small>
							{% if pokemon.shiny %}
								<small><span class="glyphicon glyphicon-star" title="shiny"></span></small>
							{% endif %}
							<br><small class="type-capsul type-{{ pokemon.pokemon.type1 }}">{{ pokemon.pokemon.type1 }}</small>
							{% if pokemon.pokemon.type2 %}
								<small class="type-capsul type-{{ pokemon.pokemon.type2 }}">{{ pokemon.pokemon.type2 }}</small>
							{% endif %}
						</div>
						<div class="col-md-12 fea text-center">
							<a href="{% url 'release_trainer_pokemon' pk=pokemon.pk %}" class="btn btn-default btn-sm">RELEASE</a>	
						</div>
					</div>
				</div>
			</div>
		{% endif %}
	{% endfor %}
{% endblock %}

trainers/templates/trainers/your_pokemons.html
{% extends 'trainers/pokemon_web_template.html' %}
{% load static %}
{% block body %}
	<div class="header-section">
		<h1>All Pokemons</h1>
		<hr>
		<hr class="bottom-line">
	</div>
	{% for pokemon in pokemons %}
		{% if pokemon.pokemon.is_verified %}
			<div class="col-md-3">
				<div class="card card-vertical card-short">
					<p>Trainer: <a href="{% url 'trainer_pokemon_list' pk=pokemon.trainer.pk %}">{{ pokemon.trainer.name }}</a></p>
					<img class="card-img-top-short" src="{{ pokemon.pokemon.photo.url }}" alt="Card image cap">
					<div class="card-body">
						<div class="col-md-12">
							<small class="text-muted">
								{% if pokemon.nickname %}
							 		{{ pokemon.nickname }}
							 	{% else %}
							 		{{ pokemon.pokemon.name }}
								{% endif %}
							</small>
							<h3 class="card-title card-title-short">
								{{ pokemon.pokemon.name }}
							</h3>
							<small>Lvl {{ pokemon.level }}</small>
							{% if pokemon.shiny %}
								<small><span class="glyphicon glyphicon-star" title="shiny"></span></small>
							{% endif %}
							<br><small class="type-capsul type-{{ pokemon.pokemon.type1 }}">{{ pokemon.pokemon.type1 }}</small>
							{% if pokemon.pokemon.type2 %}
								<small class="type-capsul type-{{ pokemon.pokemon.type2 }}">{{ pokemon.pokemon.type2 }}</small>
							{% endif %}
						</div>
						<div class="col-md-12 fea text-center">
							<a href="{% url 'release_trainer_pokemon' pk=pokemon.pk %}" class="btn btn-default btn-sm">RELEASE</a>	
						</div>
					</div>
				</div>
			</div>
		{% endif %}
	{% endfor %}
{% endblock %}

trainers/templates/trainers/your_trainers.html
{% extends 'trainers/pokemon_web_template.html' %}
{% load static %}
{% block body %}
	<div class="row">
		<div class="header-section text-center">
			<h1>Welcome, {{ user.username }} </h1>
			<p>Here is the list of trainers you've created.</p>
			<hr class="bottom-line">
		</div>
		{% for trainer in trainers %}
			<div class="col-md-4 col-sm-6">
				<div class="card card-trainer">
					<img class="card-img-top" src="{{ trainer.photo.url }}" alt="Card image cap">
					<div class="card-body">
						<h5 class="card-title">{{ trainer.name }}</h5>
						<p class="card-text">{{ trainer.get_sex_display }}</p>
						<a href="{% url 'trainer_pokemon_list' pk=trainer.pk %}" class="btn btn-primary btn-sm">View Pokemons</a>
						<div class="fea">
						  	<a href="{% url 'edit_trainer' pk=trainer.pk %}"  class="btn btn-default btn-sm" title="edit trainer"><span class="glyphicon glyphicon-pencil"></span></a> 
						  	<a href="{% url 'remove_trainer' pk=trainer.pk %}" class="btn btn-default btn-sm" title="delete trainer"><span class="glyphicon glyphicon-remove"></span></a>
						</div>
					</div>
				</div>
			</div>
		{% endfor %}
		<div class="col-md-4 col-sm-6">
			<div class="card">
				<a class="btn btn-icon" href="{% url 'create_trainer' %}" title="add trainer"><i class="glyphicon glyphicon-plus"></i></a>
			</div>
		</div>
	</div>
{% endblock %}